version: '3.8'

services:
  awshelper:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7829:80"
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development