version: '3.8'

services:
  awshelper:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7829:80"
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: awshelperdb
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: